### ISSUE TITLE
Workspace is empty

### ISSUE THREAD

**Issue by WhiteBlackGoose** [ionide/Ionide-vim#60]
Hi, thanks for this plugin.

**Describe the bug**
I'm opening an F# project, nothing happens. I even set the backend to `nvim` just in case, still.

I also tried `FSharpReloadWorkspace`, which gives me `[FSAC] Workspace is empty`.

I've also seen in the docs command `FSharpLoadWorkspaceAuto`, however, I can't run this command at all, it says that there's no such command.

**To Reproduce**

My "setup":
```lua
Plug 'ionide/Ionide-vim'
vim.g['fsharp#backend'] = 'nvim'
```

**Expected behaviour**

I'd expect some highlights, errors shown, and those commands to work. Clearly something didn't load.

**Screenshots**

![image](https://user-images.githubusercontent.com/31178401/188129002-4488c8ac-f31a-4e03-8571-309445d0d795.png)

If I go to `fsproj`, here's what it yields on saving the file:
![image](https://user-images.githubusercontent.com/31178401/188129176-fc0adfd3-b143-4a32-aac3-316560a89445.png)

**Environment (please complete the following information):**
 - OS: ubuntu 22.04
 - Neovim version: 0.7.0
 - dotnet SDK version: 6.0.301

**Comment by cannorin** [comment]
I believe Ionide-vim is failing to receive the `fsharp/notifyWorkspace` notification from fsautocomplete.

Other than that, I do believe it's actually working under the hood. I just confirmed this minimum example works with nvim 0.7 and a newly created F# project with `dotnet new console -lang F#`.

```vim
set nocompatible

syntax on
filetype plugin on

call plug#begin('~/.vim/plugged')

Plug 'ionide/Ionide-vim'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'deoplete-plugins/deoplete-lsp'

call plug#end()

let g:deoplete#enable_at_startup = 1
```

> Note that you won't get autocompletion unless you install some autocompletion plugin (such as deoplete).

Also, `FSharpLoadWorkspaceAuto` was deprecated a while ago and it shouldn't be in the docs. Can you let me know where do you find it?

**Comment by WhiteBlackGoose** [comment]
> Also, FSharpLoadWorkspaceAuto was deprecated a while ago and it shouldn't be in the docs. Can you let me know where do you find it?

[on the website](https://ionide.io/Editors/Vim/usage.html)

> Note that you won't get autocompletion unless you install some autocompletion plugin (such as deoplete).

But I should be at least getting error highlight, right? I mean, I do have deoplete but I have a whole mess with auto completion plugins and settings, so can't 100% guarantee that it's up. I just wanted to see at least some reaction, but I think Ionide just doesn't find/see the project.

> I believe Ionide-vim is failing to receive the fsharp/notifyWorkspace notification from fsautocomplete, so Ionide-vim is thinking there is no workspace loaded.

How can I diognise more, what's failing for me?

**Comment by cannorin** [comment]
> on the website

Ahh, it seems I forgot to update the website for a while. Please refer to this repository's README in the meantime.

> But I should be at least getting error highlight, right?

Yes, you should get something like this if everything is working correctly:
![WindowsTerminal_zKQCnEBHyA](https://user-images.githubusercontent.com/13620400/188159725-9d55fe06-2e4e-4d57-8fe8-0b834ea219a9.png)

If that's not the case, it might be that FSAC is failing to load the project. This is known to be a bit tricky to fix, but the general suggestions are:
* Try running `dotnet clean`, `dotnet restore`, and `dotnet build` to refresh the build.
* Removing `bin` and `obj` directories before `dotnet restore` might also help.
* If you also use Ionide-VSCode, try opening the project with it too.

> How can I diognise more, what's failing for me?

 Ionide-vim asks FsAutoComplete to hit the callback once the workspace is loaded, but I suspect it went broken because of FSAC and Neovim updates. Don't worry, I'll handle this.

**Comment by cannorin** [comment]
Fixed in https://github.com/ionide/Ionide-vim/commit/a0685e9184c75beb6c608d783389d95446775c93. It was because of the breaking changes of Neovim's LSP API.

**Comment by WhiteBlackGoose** [comment]
Thanks for your work!

However, it still doesn't load for me (I did `:PlugUpdate` and verified that it's on the latest commit).

Maybe I'm missing something else? It just doesn't do anything
> Try running dotnet clean, dotnet restore, and dotnet build to refresh the build.

Tried, no result

> Removing bin and obj directories before dotnet restore might also help.

Tried, no result

> If you also use Ionide-VSCode, try opening the project with it too

Ionide in VSC reports errors and warnings as expected

**Comment by WhiteBlackGoose** [comment]
I installed `fsautocomplete` via `mason` instead of global tool and now it works!
